cloud: Dev Mangukiya
region: us-west-2

head_node_type:
  name: head_node_type
  instance_type: m7i-flex.large

worker_node_types:
- name: cpu_worker
  instance_type: m7i-flex.large
  min_workers: 0
  max_workers: 4
  use_spot: false

aws:
  BlockDeviceMappings:
  - DeviceName: "/dev/sda1"
    Ebs:
      VolumeSize: 50
      DeleteOnTermination: true

  TagSpecifications:
  - ResourceType: instance
    Tags:
      - Key: as-feature-multi-zone
        Value: "false"
